# constants.py
# Configuration constants for the CT Scanner discrete event simulation

SHOWUP_PROBABILITY = 0.84

NUM_CHAIRS = 3
NUM_SCANNERS_OFFICE_HOURS = 1
NUM_SCANNERS_OUTSIDE_OFFICE_HOURS = 1

SLOTS_PER_DAYPART = 16
MAX_SCHEDULED_OUTPATIENTS_MORNING = 4
MAX_SCHEDULED_OUTPATIENTS_AFTERNOON = 3
